name: Build and Publish Site

on:
  push:
    paths:
      - 'content/**'
      - pelicanconf.py
      - requirements.txt
      - .github/workflows/build-and-publish.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools==57.5.0
        pip install -r requirements.txt

    - name: Run black on content
      run: |
        black content
    
    - name: Generate with Pelican
      run: |
        pelican -D content

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: output # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch